import { scenario } from './scenario';

export type KnowledgeStatus = 'source_fact' | 'proposed_scenario' | 'verified_legal_rule' | 'needs_verification';
export type KnowledgeEntry = {
  id: string; title: string; body: string; category: string; status: KnowledgeStatus;
  sourceTitle: string; sourceUrl?: string; localReference?: string; sections?: string;
  verifiedAt?: string; version: number; namespace: 'healthpod-bd'; active: boolean;
};

const doc = 'HealthPod BD Business Idea Submission, pp. 1–4';
const competition = 'Business Law Poster Competition Summer 2026, pp. 1–4';
const date = '2026-10-01';
const e = (entry: Omit<KnowledgeEntry, 'version' | 'namespace' | 'active'>): KnowledgeEntry => ({...entry, version: 1, namespace: 'healthpod-bd', active: true});

export const approvedKnowledge: KnowledgeEntry[] = [
  e({id:'concept',title:'Confirmed HealthPod concept',category:'business',status:'source_fact',sourceTitle:doc,localReference:'docs/HealthPod_BD_Business_Idea_Submission_Next Venture.pdf, pp. 1–3',body:'HealthPod BD is a proposed network of self-service booths in busy Bangladeshi public places for basic blood pressure, blood glucose and SpO₂ measurements. The intent is convenient monitoring, a clear report and general guidance, not replacing doctors or clinics. Possible users include students, office workers, commuters, shoppers and older adults. Possible sites include universities, malls, metro stations, offices and transport hubs. Revenue may come from per-check fees, memberships, hospital or diagnostic-centre partnerships, and corporate wellness. No operating booths, signed partners, price list, medical licence, device accuracy or incorporation is confirmed.'}),
  e({id:'competition',title:'Competition requirements',category:'competition',status:'source_fact',sourceTitle:competition,localReference:'docs/Business Law Poster Competition Summer 2026 (1).pdf, pp. 1–4',body:'The UIU competition requires one connected business story integrating the Contract Act 1872, Sale of Goods Act 1930, Negotiable Instruments Act 1881, Companies Act 1994 and Partnership Act 1932. The crisis and business concept require instructor approval. Judges test the chatbot, concept video, legal analysis and authentic AI fact-check evidence. The team has not supplied a confirmed final crisis or original AI error transcript.'}),
  e({id:'scenario',title:'Proposed fictional equipment dispute',category:'scenario',status:'proposed_scenario',sourceTitle:'HealthPod BD proposed competition scenario',localReference:'src/content/scenario.ts',body:`Status: ${scenario.status}, fictional and subject to team/instructor confirmation. HealthPod plans to be a private limited company. It orders ${scenario.kits} kits at BDT ${scenario.kitPriceBdt} each, BDT ${scenario.orderBdt} total, from fictional Supplier Partnership. Both supplier partners sign supply and refund agreements. ${scenario.defectiveKits} kits fail agreed specifications during inspection and are kept out of service. The parties negotiate return and BDT ${scenario.negotiatedRefundBdt} refund. A cheque drawn from the supplier firm's account is returned for insufficient funds. The negotiated refund is not an automatic right in every defective-goods dispute; no recovery or conviction is established. A judge's altered facts are hypotheticals, not corrections to this saved scenario.`}),
  e({id:'contract-10-37',title:'Contract formation and performance',category:'law',status:'verified_legal_rule',sourceTitle:'Contract Act 1872, sections 10 and 37',sourceUrl:'https://bdlaws.minlaw.gov.bd/act-26.html',sections:'10, 37',verifiedAt:date,body:'Section 10 describes when agreements are contracts, including free consent, competent parties, lawful consideration and object, and no express voidness, subject to other writing/registration laws. Section 37 requires parties to perform or offer to perform their promises unless performance is legally excused. In the proposed scenario, examine the signed supply specifications and negotiated settlement, including authority to sign and any condition.'}),
  e({id:'contract-73',title:'Contract compensation',category:'law',status:'verified_legal_rule',sourceTitle:'Contract Act 1872, section 73',sourceUrl:'https://bdlaws.minlaw.gov.bd/act-26/section-259.html',sections:'73',verifiedAt:date,body:'Section 73 provides compensation for loss or damage caused by breach that naturally arose in the usual course or that parties knew was likely when contracting; it excludes remote and indirect loss, and the means of remedying inconvenience must be considered. A party must establish breach, causation and supported loss. It does not guarantee every demanded amount or specific performance.'}),
  e({id:'goods-12-16',title:'Goods: conditions, description, quality',category:'law',status:'verified_legal_rule',sourceTitle:'Sale of Goods Act 1930, sections 12, 13, 15 and 16',sourceUrl:'https://bdlaws.minlaw.gov.bd/act-print-150.html',sections:'12, 13, 15, 16',verifiedAt:date,body:'Section 12 distinguishes conditions from warranties. Section 13 includes circumstances in which breach of condition is treated as breach of warranty, including qualified consequences after acceptance. Section 15 concerns sale by description. Section 16 gives qualified implied quality/fitness rules with exceptions; there is no blanket guarantee. Compare actual devices with agreed description/specifications, and determine whether the term is a condition or warranty and whether acceptance changes remedies.'}),
  e({id:'goods-41-42',title:'Goods: examination and acceptance',category:'law',status:'verified_legal_rule',sourceTitle:'Sale of Goods Act 1930, sections 41–42',sourceUrl:'https://bdlaws.minlaw.gov.bd/act-150/act-chapter-print-406.html',sections:'41–42',verifiedAt:date,body:'Section 41 gives a buyer who has not previously examined goods a reasonable opportunity to examine conformity before deemed acceptance; unless otherwise agreed, the seller must afford reasonable examination on request. Section 42 identifies acceptance through intimation, acts inconsistent with seller ownership, or retention beyond a reasonable time without rejection notice. If goods were already accepted, do not promise rejection; inspect the contract and other possible remedies.'}),
  e({id:'partnership-4-19-25',title:'Supplier partnership and responsibility',category:'law',status:'verified_legal_rule',sourceTitle:'Partnership Act 1932, sections 4, 18–19 and 25',sourceUrl:'https://bdlaws.minlaw.gov.bd/act-print-157.html',sections:'4, 18–19, 25',verifiedAt:date,body:'Section 4 defines partnership as a relation between persons who agree to share profits of a business carried on by all or any acting for all. Section 18 describes a partner as the agent of the firm for business purposes. Section 19 states a partner’s acts in the usual way of the firm’s business can bind the firm, subject to its qualifications. Section 25 makes partners jointly and severally liable for acts of the firm while partners. Here this law applies to the fictional supplier, not HealthPod shareholders. Both supplier partners signed in the base scenario. If authority is disputed in a new hypothetical, check the deed, signatures, scope of business and what the buyer knew. Civil partner liability is not automatic cheque criminal guilt.'}),
  e({id:'company-formation',title:'Company formation and separate identity',category:'law',status:'verified_legal_rule',sourceTitle:'Companies Act 1994, sections 5 and 24',sourceUrl:'https://bdlaws.minlaw.gov.bd/act-788.html',sections:'5, 24',verifiedAt:date,body:'Section 5 concerns formation of an incorporated company by subscribing to the memorandum and complying with registration requirements. Section 24 addresses the effect of registration and corporate existence. HealthPod only plans a private limited company; there is no evidence of actual registration. Before a purchase or settlement, founders should check its constitutional documents and recorded authority. Limited company status does not imply blanket immunity for directors or other individuals.'}),
  e({id:'cheque-138-141',title:'Dishonoured cheque conditions and procedure',category:'law',status:'verified_legal_rule',sourceTitle:'Negotiable Instruments Act 1881, sections 138, 140 and 141',sourceUrl:'https://bdlaws.minlaw.gov.bd/act-46/act-chapter-print-150.html',sections:'138, 140, 141',verifiedAt:date,body:'Section 138 concerns specified cheque dishonour and has requirements for presentation, written demand notice and nonpayment after receipt. Section 140 includes firms in its definition and differentiates responsible persons, knowledge and due diligence; being a partner alone is not an automatic conviction. Section 141 specifies complaint and timing requirements. The exact instrument, account holder, bank memo, date of presentation, notice, service and complaint must be reviewed under current Bangladesh text. A returned cheque alone does not prove an offence or guarantee recovery. Civil recovery questions are distinct.'}),
  e({id:'operational-open',title:'Open operational questions',category:'business',status:'needs_verification',sourceTitle:doc,localReference:'docs/HealthPod_BD_Business_Idea_Submission_Next Venture.pdf',body:'Before any real booth service, the team must resolve glucose-testing method, hygiene, consent, equipment validation and applicable operational approvals. The current source does not establish non-invasive glucose sensing, diagnostic accuracy, a licence, or approval. The chatbot does not interpret a visitor’s medical reading.'}),
  e({id:'team-next-venture',title:'Next Venture Team & UIU Course Information',category:'team',status:'source_fact',sourceTitle:'Next Venture Team Profile · UIU LAW 4151/2106',localReference:'src/content/team.ts',body:'HealthPod BD was conceived and built by team Next Venture for the Business Law Poster Competition (LAW 4151 / 2106, Section B, Summer 2026) at United International University (UIU). Team members: 1. Shifa Akter Mim (Student ID: 111221166), 2. Asif Hossain (Student ID: 111221086), 3. Tanzir Ahsan Shakib (Student ID: 1112230189), 4. Md. Nahidul Islam (Student ID: 1112230203).'}),
  e({id:'booth-hardware',title:'HealthPod BD Hardware & Sensor Capabilities',category:'product',status:'source_fact',sourceTitle:'HealthPod BD Technical Architecture',localReference:'docs/HealthPod_BD_Codex_Build_Brief.md',body:'HealthPod BD self-service booths integrate certified screening hardware: 1. Automated digital blood pressure & pulse cuff (systolic, diastolic, pulse rate), 2. High-precision fingertip SpO2 pulse oximeter (blood oxygen saturation), 3. Blood glucose monitoring with automated sanitization, 4. Non-contact infrared temperature sensor, 5. Built-in digital scale and height meter for automatic BMI calculation. Features an interactive touch terminal, bilingual voice guidance (Bangla & English), mobile QR sync for test reports, and UV/sanitizer self-cleaning between users.'}),
  e({id:'business-model',title:'HealthPod BD Business & Revenue Model',category:'business',status:'source_fact',sourceTitle:'HealthPod BD Business Plan',localReference:'docs/HealthPod_BD_Business_Idea_Submission_Next Venture.pdf',body:'HealthPod BD operates on a sustainable multi-stream revenue model: 1. Pay-per-check micropayments via bKash/Nagad (BDT 50-100 per biometric assessment), 2. Subscription memberships for frequent commuters/students (discounted monthly health tracking), 3. B2B corporate wellness contracts for office employees, 4. Qualified referral partnerships with licensed hospitals and diagnostic centers when abnormal readings suggest clinical follow-up.'}),
  e({id:'five-laws-overview',title:'Overview of 5 Bangladeshi Commercial Laws in HealthPod BD',category:'law',status:'verified_legal_rule',sourceTitle:'UIU Business Law (LAW 4151/2106) & Bangladesh Statutes',sourceUrl:'https://bdlaws.minlaw.gov.bd',sections:'All 5 Statutes',verifiedAt:date,body:'HealthPod BD connects five core Bangladesh commercial statutes: 1. Companies Act 1994 (incorporation & separate corporate persona), 2. Partnership Act 1932 (supplier partnership governance & partner liability), 3. Contract Act 1872 (supply agreement terms & breach remedies), 4. Sale of Goods Act 1930 (device conformity, implied condition & acceptance), 5. Negotiable Instruments Act 1881 (dishonour of refund cheque & legal notices).'})
];

export const approvedSource = (entry: KnowledgeEntry) => ({id:entry.id,title:entry.sourceTitle,...(entry.sourceUrl?{url:entry.sourceUrl}:{}),...(entry.sections?{section:entry.sections}:{})});
